cpu: 1
mem: 1
load: 1
disk: 1
net: 1
disk-opts:
  names:
    - sda1
#flushPath: /tmp/noderig
#listen: none

# To keep always the last value of a custom collector you can set:
#keep-metrics: true
#keep-for: 1